title = "Danskin Clouds"
summary = """An oft expressed intention was finally made real as my neighbor and I got out for a ride together. For a solid five hours, I saw the world without made-up political memes. At first my eyes stung but slowly they adjusted to the lack of hyperbole."""
cover_photo_index = 20

[categories]
who = "Friends"
when = 2016
where = ["Danskin"]
what = "KTM 500 XC-W"